extern const GeoLayout koopa_shell_geo[];
extern const GeoLayout koopa_shell2_geo[];
extern const GeoLayout koopa_shell3_geo[];
extern Lights1 koopa_shell_mat_shell_lights;
extern u8 koopa_shell_nokonoko_shell_rgba16[];
extern Vtx koopa_shell_000_displaylist_mesh_layer_4_vtx_0[98];
extern Gfx koopa_shell_000_displaylist_mesh_layer_4_tri_0[];
extern Gfx mat_koopa_shell_mat_shell[];
extern Gfx koopa_shell_000_displaylist_mesh_layer_4[];
extern Gfx koopa_shell_material_revert_render_settings[];
