extern const GeoLayout yellow_coin_geo[];
extern const GeoLayout yellow_coin_no_shadow_geo[];
extern const GeoLayout red_coin_geo[];
extern const GeoLayout red_coin_no_shadow_geo[];
extern const GeoLayout blue_coin_geo[];
extern const GeoLayout blue_coin_no_shadow_geo[];
extern Lights1 coin_coin_f3d_lights;
extern u8 coin_coin_yellow01_rgba16[];
extern u8 coin_coin_redstar01_rgba16[];
extern u8 coin_coin_bluestar01_rgba16[];
extern Vtx coin_000_displaylist_mesh_layer_1_vtx_0[41];
extern Gfx coin_000_displaylist_mesh_layer_1_tri_0[];
extern Gfx mat_coin_coin_f3d[];
extern Gfx mat_coin_coin_red_f3d[];
extern Gfx mat_coin_coin_blue_f3d[];
extern Gfx coin_000_displaylist_mesh_layer_1[];
extern Gfx coin_001_displaylist_mesh_layer_1[];
extern Gfx coin_002_displaylist_mesh_layer_1[];
extern Gfx coin_material_revert_render_settings[];
