#include "src/game/envfx_snow.h"

const GeoLayout koopa_Koopa_Troopa_Closed_Eyes_Head[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_ALPHA, 104, -26, 0, koopa_001_switch_option_001_offset_mesh_layer_4),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout koopa_with_shell_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SHADOW(0, 155, 100),
		GEO_OPEN_NODE(),
			GEO_SCALE(LAYER_FORCE, 16384),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, koopa_000_offset_001_mesh_layer_4),
					GEO_OPEN_NODE(),
						GEO_SWITCH_CASE(2, geo_switch_anim_state),
						GEO_OPEN_NODE(),
							GEO_NODE_START(),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_ALPHA, 106, -25, 0, koopa_000_offset_002_mesh_layer_4),
							GEO_CLOSE_NODE(),
							GEO_BRANCH(1, koopa_Koopa_Troopa_Closed_Eyes_Head),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, -14, -5, 34, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, koopa_000_offset_003_mesh_layer_4),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(LAYER_ALPHA, koopa_000_offset_004_skinned_mesh_layer_4),
								GEO_ANIMATED_PART(LAYER_ALPHA, 73, -13, 26, koopa_000_offset_004_mesh_layer_4),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, -14, -5, -33, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, koopa_000_offset_005_mesh_layer_4),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(LAYER_ALPHA, koopa_000_offset_006_skinned_mesh_layer_4),
								GEO_ANIMATED_PART(LAYER_ALPHA, 73, -13, -27, koopa_000_offset_006_mesh_layer_4),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 73, -24, -40, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, koopa_000_offset_007_mesh_layer_4),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(LAYER_ALPHA, koopa_000_offset_008_skinned_mesh_layer_4),
								GEO_ANIMATED_PART(LAYER_ALPHA, 80, -29, -28, koopa_000_offset_008_mesh_layer_4),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 73, -24, 41, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, koopa_000_offset_009_mesh_layer_4),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(LAYER_ALPHA, koopa_000_offset_010_skinned_mesh_layer_4),
								GEO_ANIMATED_PART(LAYER_ALPHA, 80, -29, 21, koopa_000_offset_010_mesh_layer_4),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(LAYER_ALPHA, koopa_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
