extern const GeoLayout boo_switch_opt1[];
extern const GeoLayout boo_geo[];
extern Lights1 boo_mat_tere_1body_f3d_v5_lights;
extern Lights1 boo_mat_tere_3tooth_f3d_v5_lights;
extern u8 boo_teresa_cmp4_rgba16[];
extern Vtx boo_skl_root_mesh_layer_1_vtx_0[80];
extern Gfx boo_skl_root_mesh_layer_1_tri_0[];
extern Vtx boo_skl_root_mesh_layer_4_vtx_0[15];
extern Gfx boo_skl_root_mesh_layer_4_tri_0[];
extern Gfx mat_boo_mat_tere_1body_f3d_v5[];
extern Gfx mat_revert_boo_mat_tere_1body_f3d_v5[];
extern Gfx mat_boo_mat_tere_3tooth_f3d_v5[];
extern Gfx mat_revert_boo_mat_tere_3tooth_f3d_v5[];
extern Gfx boo_skl_root_mesh_layer_1[];
extern Gfx boo_skl_root_mesh_layer_4[];
extern Gfx boo_material_revert_render_settings[];
